import Link from "next/link";
import { ArrowUpRight, Check, ChevronRight, Circle, GitBranch, LockKeyhole, Radar, ShieldCheck, Sparkles } from "lucide-react";

export default function LandingPage() {
  return <main className="min-h-screen overflow-hidden bg-ink text-paper"><div className="grid-fade pointer-events-none absolute inset-x-0 top-0 h-[620px] opacity-60" />
    <nav className="relative mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg border border-teal/40 bg-teal/10 text-teal"><ShieldCheck size={18} /></div><div><div className="text-sm font-bold">AegisFlow</div><div className="font-mono text-[9px] uppercase tracking-[.24em] text-muted">security workflows</div></div></div><div className="flex items-center gap-3"><Link href="/login" className="rounded-lg px-3 py-2 text-sm text-muted hover:text-paper">Sign in</Link><Link href="/signup" className="rounded-lg bg-paper px-4 py-2 text-sm font-semibold text-ink hover:bg-white">Open workspace <ArrowUpRight size={14} className="ml-1 inline" /></Link></div></nav>
    <section className="relative mx-auto grid max-w-7xl gap-14 px-6 pb-24 pt-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-10 lg:pb-36 lg:pt-28"><div><div className="mb-7 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.24em] text-teal"><span className="h-1.5 w-1.5 rounded-full bg-teal" /> evidence-first security automation</div><h1 className="max-w-3xl font-display text-6xl leading-[.9] tracking-[-.04em] text-paper sm:text-7xl lg:text-[7.6rem]">Turn a scan into a <em className="text-teal">chain of proof.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted">AegisFlow coordinates deterministic security agents around the work your team actually owns — preserving evidence, scope, and limitations at every step.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/signup" className="rounded-lg bg-teal px-5 py-3 text-sm font-bold text-ink hover:bg-[#73e6d4]">Start with a source review <ArrowUpRight size={15} className="ml-1 inline" /></Link><Link href="#architecture" className="rounded-lg border border-line px-5 py-3 text-sm font-semibold text-paper hover:border-teal/60">See the workflow</Link></div><div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 font-mono text-[10px] uppercase tracking-[.16em] text-muted"><span><Check size={13} className="mr-1 inline text-teal" /> no LLM required</span><span><Check size={13} className="mr-1 inline text-teal" /> safe by default</span><span><Check size={13} className="mr-1 inline text-teal" /> persisted findings</span></div></div>
      <div className="relative"><div className="absolute -inset-8 rounded-full bg-teal/5 blur-3xl" /><div className="relative rounded-2xl border border-line bg-panel p-4 shadow-panel"><div className="flex items-center justify-between border-b border-line px-3 pb-4"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-teal" /><span className="font-mono text-[10px] uppercase tracking-[.18em] text-muted">live assessment / 04</span></div><span className="rounded-full border border-teal/20 bg-teal/10 px-2 py-1 font-mono text-[9px] text-teal">RUNNING</span></div><div className="grid gap-3 p-3 sm:grid-cols-[1fr_1.15fr]"><div className="space-y-2">{[["Planner", "completed", "text-teal"], ["Coordinator", "completed", "text-teal"], ["Source Agent", "running", "text-amber"], ["Validator", "pending", "text-muted"], ["Report", "pending", "text-muted"]].map(([name, state, color], i) => <div key={name} className="flex items-center gap-3 rounded-lg border border-line bg-ink/60 px-3 py-3"><div className={`grid h-7 w-7 place-items-center rounded-md border border-line bg-panel2 ${color}`}><span className="font-mono text-[10px]">0{i + 1}</span></div><div className="min-w-0 flex-1"><div className="text-xs font-semibold">{name}</div><div className="font-mono text-[9px] uppercase tracking-[.14em] text-muted">{state}</div></div><ChevronRight size={14} className="text-line" /></div>)}</div><div className="rounded-xl border border-line bg-ink/80 p-4"><div className="mb-8 flex items-center justify-between"><div><div className="font-mono text-[9px] uppercase tracking-[.18em] text-muted">evidence captured</div><div className="mt-1 text-3xl font-semibold">07</div></div><Radar size={22} className="text-teal" /></div><div className="space-y-5">{[["Hardcoded credential signal", "high", "w-[74%] bg-coral"], ["Dynamic execution sink", "high", "w-[58%] bg-coral/70"], ["Disabled TLS verification", "medium", "w-[36%] bg-amber"]].map(([label, severity, bar]) => <div key={label}><div className="mb-2 flex justify-between text-[11px]"><span className="text-paper">{label}</span><span className="font-mono text-[9px] uppercase text-muted">{severity}</span></div><div className="h-1.5 rounded-full bg-line"><div className={`h-1.5 rounded-full ${bar}`} /></div></div>)}</div><div className="mt-10 border-t border-line pt-3 font-mono text-[9px] uppercase tracking-[.14em] text-muted"><Circle size={9} className="mr-1 inline fill-teal text-teal" /> source-security / fallback rules</div></div></div></div></div>
    </section>
    <section id="architecture" className="border-y border-line bg-[#0d1215] px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="mb-12 max-w-xl"><div className="font-mono text-[10px] uppercase tracking-[.22em] text-teal">designed for accountable automation</div><h2 className="mt-4 font-display text-5xl leading-none tracking-[-.03em]">Every agent leaves a trace.</h2><p className="mt-5 text-muted">From first scope decision to final remediation, AegisFlow stores the task state, execution logs, evidence, and limitations that make an assessment reviewable.</p></div><div className="grid gap-3 md:grid-cols-3">{[[GitBranch, "Orchestrated", "Dependency-aware tasks, bounded retries, and transactional claims keep agent work legible."], [LockKeyhole, "Scoped", "Explicit authorization and verified origins come before any live website request."], [Sparkles, "Evidence-first", "Findings are grounded in observed code or response metadata, never invented by a model."]].map(([Icon, title, copy]) => <div key={title as string} className="rounded-2xl border border-line bg-panel p-6"><Icon size={20} className="text-teal" /><h3 className="mt-12 text-lg font-semibold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-muted">{copy as string}</p></div>)}</div></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-4 px-6 py-8 text-xs text-muted sm:flex-row sm:items-center sm:justify-between lg:px-10"><span>AEGISFLOW / IDP IMPLEMENTATION REVIEW / 2026</span><span className="font-mono">BUILDING TRUST INTO THE LOOP</span></footer>
  </main>;
}
