import Link from "next/link";
import { ArrowUpRight, Bot, CheckCircle2, CircleDashed, FolderKanban, Plus, ShieldAlert, Timer } from "lucide-react";
import { Badge, Panel } from "@/components/ui";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { formatDate, formatRelative } from "@/lib/utils";
import type { Finding, Project, Scan } from "@/types";

export default async function DashboardPage() {
  const client = await createSupabaseServerClient();
  const [{ data: projects }, { data: scans }, { data: findings }] = client ? await Promise.all([
    client.from("projects").select("id,name,description,created_at,updated_at").order("updated_at", { ascending: false }).limit(5),
    client.from("scans").select("id,project_id,status,created_at,started_at,completed_at,scope,projects(name)").order("created_at", { ascending: false }).limit(6),
    client.from("findings").select("id,title,severity,kind,agent_id,created_at").order("created_at", { ascending: false }).limit(8),
  ]) : [{ data: [] }, { data: [] }, { data: [] }];
  const projectRows = (projects ?? []) as Project[]; const scanRows = (scans ?? []) as unknown as (Scan & { projects?: { name: string } | null })[]; const findingRows = (findings ?? []) as Pick<Finding, "id"|"title"|"severity"|"kind"|"agent_id"|"created_at">[];
  const counts = { critical: findingRows.filter(f=>f.severity === "critical").length, high: findingRows.filter(f=>f.severity === "high").length, medium: findingRows.filter(f=>f.severity === "medium").length, low: findingRows.filter(f=>f.severity === "low").length };
  const completed = scanRows.filter(s=>s.status === "completed" || s.status === "partially_completed").length;
  return <div className="mx-auto max-w-[1480px] space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="font-mono text-[10px] uppercase tracking-[.22em] text-teal">overview / sept 21, 2026</div><h1 className="mt-2 font-display text-5xl leading-none tracking-[-.03em]">Good morning, Rahul.</h1><p className="mt-3 text-sm text-muted">A clear view of what your agents know — and what they don’t.</p></div><Link href="/projects/new" className="inline-flex items-center justify-center gap-2 rounded-lg bg-teal px-4 py-2.5 text-sm font-bold text-ink hover:bg-[#73e6d4]"><Plus size={15}/> New project</Link></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[FolderKanban,"Projects",String(projectRows.length),"active workspaces","text-ice"],[ShieldAlert,"Findings",String(findingRows.length),"latest persisted observations","text-coral"],[Timer,"Assessments",String(scanRows.length),`${completed} completed`,"text-amber"],[Bot,"Agent runs",String(scanRows.length * 3),"task executions recorded","text-teal"]].map(([Icon,label,value,sub,color])=><Panel key={label as string} className="p-5"><div className="flex items-center justify-between"><span className="text-sm text-muted">{label as string}</span><Icon size={17} className={color as string}/></div><div className="mt-6 text-4xl font-semibold tracking-tight">{value as string}</div><div className="mt-2 font-mono text-[9px] uppercase tracking-[.14em] text-muted">{sub as string}</div></Panel>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Panel><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-semibold">Recent assessments</h2><p className="mt-1 text-xs text-muted">Live state from the orchestration queue</p></div><Link href="/projects" className="text-xs text-teal hover:underline">View all <ArrowUpRight size={12} className="inline"/></Link></div><div className="divide-y divide-line">{scanRows.length ? scanRows.map(scan=><Link href={`/projects/${scan.project_id}/scans/${scan.id}`} key={scan.id} className="flex items-center gap-4 px-5 py-4 hover:bg-panel2"><div className="grid h-9 w-9 place-items-center rounded-lg border border-line bg-ink text-muted">{scan.status === "completed" ? <CheckCircle2 size={16} className="text-teal"/> : <CircleDashed size={16} className="text-amber"/>}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{scan.projects?.name ?? "Assessment"}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[.14em] text-muted">{scan.status} · {formatRelative(scan.created_at)}</div></div><Badge tone={scan.status === "completed" ? "teal" : scan.status === "failed" ? "coral" : "amber"}>{scan.status.replaceAll("_", " ")}</Badge></Link>) : <div className="px-5 py-12 text-center text-sm text-muted">No assessments yet. Create a project and upload a source artifact to start.</div>}</div></Panel>
      <Panel><div className="border-b border-line px-5 py-4"><h2 className="text-sm font-semibold">Findings by severity</h2><p className="mt-1 text-xs text-muted">Latest persisted records</p></div><div className="space-y-5 p-5">{[["Critical",counts.critical,"bg-coral"],["High",counts.high,"bg-coral/70"],["Medium",counts.medium,"bg-amber"],["Low",counts.low,"bg-ice"]].map(([label,value,color])=><div key={label as string}><div className="mb-2 flex justify-between text-xs"><span>{label as string}</span><span className="font-mono text-[10px] text-muted">{value as number}</span></div><div className="h-2 rounded-full bg-line"><div className={`h-2 rounded-full ${color as string}`} style={{width:`${Math.max(4,Math.min(100,(value as number)/(Math.max(findingRows.length,1))*100))}%`}}/></div></div>)}</div><div className="border-t border-line px-5 py-4"><Link href="/activity" className="text-xs text-teal hover:underline">Open activity stream <ArrowUpRight size={12} className="inline"/></Link></div></Panel></div>
    <Panel><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-semibold">Recent evidence</h2><p className="mt-1 text-xs text-muted">Findings are observations, not invented scores.</p></div><span className="font-mono text-[9px] uppercase tracking-[.15em] text-muted">{formatDate(findingRows[0]?.created_at)}</span></div><div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-4">{findingRows.slice(0,4).map(f=><div key={f.id} className="rounded-xl border border-line bg-ink/60 p-4"><div className="flex items-center justify-between"><Badge tone={f.severity === "high" || f.severity === "critical" ? "coral" : f.severity === "medium" ? "amber" : "ice"}>{f.severity}</Badge><span className="font-mono text-[9px] text-muted">{f.agent_id}</span></div><div className="mt-4 line-clamp-2 text-sm font-semibold leading-5">{f.title}</div><div className="mt-3 text-xs text-muted">{formatRelative(f.created_at)}</div></div>)}</div></Panel>
  </div>;
}
