"use client";
import { useMemo } from "react";
import ReactFlow, { Background, Controls, Edge, Node } from "reactflow";
import "reactflow/dist/style.css";
import { cn } from "@/lib/utils";

type Task = { id:string; agent_id:string; status:string; output?:{findings?:unknown[]}|null };
const labels: Record<string,string> = { planner:"Planner", coordinator:"Coordinator", "web-security":"Web Agent", "source-security":"Source Agent", validator:"Validator", report:"Report Agent" };
export function WorkflowGraph({ tasks }: { tasks: Task[] }) { const byAgent=useMemo(()=>new Map(tasks.map(t=>[t.agent_id,t])),[tasks]); const order=["planner","coordinator","web-security","source-security","validator","report"];const nodes:Node[]=order.map((agent,index)=>{const task=byAgent.get(agent);return {id:agent,position:{x:agent==="web-security"?170:agent==="source-security"?390:(index%2)*190,y:Math.floor(index/2)*120},data:{label:<div className="min-w-[150px] rounded-xl border border-line bg-panel px-3 py-3"><div className="font-mono text-[9px] uppercase tracking-[.14em] text-muted">{agent}</div><div className="mt-2 text-xs font-semibold">{labels[agent]}</div><div className={cn("mt-2 text-[9px] uppercase tracking-[.14em]",task?.status==="completed"?"text-teal":task?.status==="running"?"text-amber":task?.status==="failed"?"text-coral":"text-muted")}>{task?.status??"not scheduled"}</div></div>},type:"default"};});const edges:Edge[]=[{id:"p-c",source:"planner",target:"coordinator"},{id:"c-s",source:"coordinator",target:"source-security"},{id:"c-w",source:"coordinator",target:"web-security"},{id:"s-v",source:"source-security",target:"validator"},{id:"w-v",source:"web-security",target:"validator"},{id:"v-r",source:"validator",target:"report"}];return <div className="h-[410px] w-full overflow-hidden rounded-xl border border-line bg-ink"><ReactFlow nodes={nodes} edges={edges} fitView fitViewOptions={{padding:.22}} nodesDraggable={false} nodesConnectable={false} panOnScroll><Background color="#263139" gap={22}/><Controls showInteractive={false}/></ReactFlow></div>; }
